# Generated by Django 4.2.2 on 2023-07-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categ_prod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEmpresa',
            fields=[
                ('id_inf_emp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombreRubro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('id_prof', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SesionesEmpleados',
            fields=[
                ('id_sesion_emp', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=20)),
                ('ape_paterno', models.CharField(max_length=20)),
                ('ape_materno', models.CharField(max_length=20, null=True)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('img_perfil', models.ImageField(null=True, upload_to='usersApp')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('id_categ_prod', models.ForeignKey(db_column='id_categ_prod', on_delete=django.db.models.deletion.CASCADE, to='usersApp.categoriaproducto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usersApp.usuario')),
            ],
        ),
    ]
