# Generated by Django 4.2.2 on 2023-07-01 08:26

from django.db import migrations, models
import django.db.models.deletion
import usersApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesiones',
            name='nombre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='calificacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_prof',
            field=models.ForeignKey(db_column='id_prof', default=0, on_delete=django.db.models.deletion.CASCADE, to='usersApp.profesiones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='id_categ_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoempresa',
            name='id_inf_emp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesiones',
            name='id_prof',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesionesempleados',
            name='id_sesion_emp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img_perfil',
            field=models.ImageField(null=True, upload_to=usersApp.models.upload_location),
        ),
    ]
