# Generated by Django 4.2.2 on 2023-07-01 09:17

from django.db import migrations, models
import django.db.models.deletion
import usersApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_comprausuario_producto_stock_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprausuario',
            name='id_user',
            field=models.ForeignKey(db_column='id_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to='usersApp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='img_perfil',
            field=models.ImageField(null=True, upload_to=usersApp.models.upload_location),
        ),
    ]
