# Generated by Django 4.2.2 on 2023-07-01 09:41

from django.db import migrations, models
import usersApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_comprausuario_id_user_producto_img_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img_perfil',
        ),
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(null=True, upload_to=usersApp.models.upload_location_prod),
        ),
        migrations.AlterField(
            model_name='comprausuario',
            name='id_compra_user',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_prod',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
