# Generated by Django 4.2.2 on 2023-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_remove_producto_img_perfil_producto_img_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='id_categ_prod',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoempresa',
            name='id_inf_emp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesiones',
            name='id_prof',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesionesempleados',
            name='id_sesion_emp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='calificacion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
