# Generated by Django 4.2.2 on 2023-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_alter_categoriaproducto_id_categ_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprausuario',
            name='id_compra_user',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoempresa',
            name='id_inf_emp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_prod',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesiones',
            name='id_prof',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesionesempleados',
            name='id_sesion_emp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
